export const skills = [
  ...new Set([
    'Interpersonal Skills',
    'Critical Thinking',
    'Problem Solving',
    'Public Speaking',
    'Customer Service Skills',
    'Teamwork Skills',
    'Communication',
    'Collaboration',
    'Accounting',
    'Active Listening',
    'Adaptability',
    'Negotiation',
    'Conflict Resolution',
    'Empathy',
    'Customer Service',
    'Decision Making',
    'Management',
    'Leadership skills',
    'Organization',
    'Language skills',
    'Administrative skills',
    'Data Entry',
    'Answering Phones',
    'Billing',
    'Scheduling',
    'Microsoft Office skills',
    'Office Equipment',
    'QuickBooks',
    'Shipping',
    'Welcoming Visitors',
    'Salesforce',
    'Calendar Management',
    'Product Knowledge',
    'Lead Qualification',
    'Lead Prospecting ',
    'Customer Needs Analysis',
    'Referral Marketing',
    'Contract Negotiation',
    'Self Motivation',
    'Increasing Customer Lifetime Value (CLV)',
    'Reducing Customer Acquisition Cost (CAC)',
    'CRM Software ',
    'POS Skills',
    'Cashier Skills',
    'Good Communication Skills',
    'General Nursing Skills',
    'Patient Assessment',
    'Taking Vital Signs',
    'Patient Care',
    'Recording Patient Medical History',
    'Wound Dressing and Care',
    'Urgent and Emergency Care',
    'Record-Keeping',
    'Patient Education',
    'NIH Stroke Scale Patient Assessment',
    'Electronic Medical Record (EMR)',
    'Medicine Administration',
    'Blood Pressure Monitoring',
    'Phlebotomy',
    'Rehabilitation Therapy',
    'Hygiene Assistance',
    'Use of X-Ray, MRI, CAT Scans',
    'Meditech',
    'Glucose Checks',
    'Electronic Heart Record (EHR)',
    'Web Development',
    'Data Structures',
    'Open Source Experience',
    'CodingJava Script',
    'Security',
    'Machine Learning',
    'Debugging',
    'UX/UI',
    'Front-End & Back-End Development',
    'Cloud Management',
    'Agile Development',
    'STEM Skills',
    'CAD',
    'Design',
    'Prototyping',
    'Testing',
    'Troubleshooting',
    'Project Launch',
    'Lean Manufacturing',
    'Workflow Development',
    'Computer Skills',
    'SolidWorks',
    'Budgeting',
    'Technical Report Writing SkillsSTEM Skills',
    'CAD',
    'Lean Manufacturing',
    'SolidWorks',
    'Technical Report Writing Skills',
    'SEO/SEM',
    'PPC',
    'CRO',
    'A/B Testing',
    'Social Media Marketing and Paid Social Media Advertising',
    'Sales Funnel Management',
    'CMS Tools',
    'Graphic Design Skills',
    'Email Marketing Skills',
    'Email Automation',
    'Data Visualization',
    'CPC',
    'Typography',
    'Print Design',
    'Photography and Branding',
    'Agile',
    'Managing Cross-Functional Teams',
    'Scrum',
    'Performance Tracking',
    'Financial Modelling',
    'Ideation Leadership',
    'Feature Definition',
    'Forecasting',
    'Profit and Loss',
    'Scope Management',
    'Project Lifecycle Management',
    'Meeting Facilitation',
    'Managerial Skills',
    'Organizing Skills',
    'Data analysis',
    'Web analytics ',
    'SEO/SEM',
    'HTML & CSS',
    'Email marketing',
    'Web scraping',
    'CRO and A/B Testing',
    'Data visualization & pattern-finding through critical thinking',
    'Search Engine and Keyword Optimization',
    'Project/campaign management',
    'Social media and mobile marketing ',
    'Paid social media advertisements',
    'B2B Marketing',
    'The 4 P-s of Marketing',
    'Consumer Behavior Drivers',
    'Brand management',
    'Copywriting',
    'Storytelling',
    'Sales',
    'CMS Tools',
    'Adobe Creative Suite: Illustrator, InDesign, Photoshop',
    'Dreamweaver',
    'Infographics',
    'HTML & CSS',
    'Photo editing ',
    'Typography: spacing, line height, layout, choosing fonts',
    'Storyboarding',
    'Targeting and marketing through visual communications',
    'Logo creation',
    'Digital printing',
    'Integration of visual communication in social media platforms',

    'Attention to detail & aesthetics',
    'Interactive media design',
    'Color sense & theory',
    'Ad design',
    'Active listening',
    'Microsoft Office Pack: Word, Excel, Access, Publisher, Outlook, Powerpoint',
    'Filing and paper management',
    'Data entry',
    'Bookkeeping through Excel or TurboTax',
    'Research and data analysis',
    'Basic knowledge of user interface communication',
    'Technical writing',
    'Cloud networking and file sharing ',
    'Microsoft Excel (Advanced)',
    'Enterprise Resource Planning ',
    'Big Data Analysis & SQL',
    'Know Your Customers (KYC)',
    'Cognos Analytics (IBM)',
    'Visual Basic',
    'Accounting Software',
    'Revenue recognition',
    'Anti Money Laundering',
    'Clear communication',
    'General business knowledge',
    'Numerical competence',
    'Technological & digital literacy',
    'HTML/CSS',
    'CSS preprocessors',
    'Javascript',
    'Wordpress',
    'Graphic User Interfaces (GUI)',
    'Git/Version control (Github, gitlab)',
    'Search Engine Optimization (SEO)',
    'Application Programming Interface (API)',
    'Adobe Photoshop, InDesign',
    'Content Management Systems (CMS)',
    'Testing/Debugging',
    'Responsive design principles',
    'SQL (a must) and Hive (optional)',
    'Programming language (R, Python, Scala, Matlab)',
    'STATA, SPSS, SAS ',
    'Data Mapping',
    'Entity Relationship Diagrams',
    'Wireframes',
    'Big Data tools ',
    'Microsoft Visio',
    'Agile Business Analysis',
    'Machine learning ',
    'System Context Diagrams',
    'Business Process Modeling',
    'Technical and non-technical communication',
    'React JS',
    'Angular JS',
    'jQuery',
    'Bootstrap',
    'Tailwind CSS',
    'Loadash',
    'Node JS',
    'Express JS',
    'Next JS',
    'D3 JS',
    'Underscore JS',
    'Anime JS',
    'Chart.JS',
    'Cleave.JS',
    'Backbone.JS',
    'Meteor JS',
    'Polymer ',
    'Svelte',
    '.NET Core',
    'PyTorch',
    'TenserFlow',
    'OpenCV',
    'django',
    'Laravel',
    'Ruby on Rails',
    'Flask',
    'ASP.NET',
    'Java',
    'TypeScript',
    'Bash/Shell',
    'C#',
    'C++',
    'C',
    'PowerShell',
    'Go',
    'Rust',
    'Kotlin',
    'Dart',
    'Assembly',
    'Swift',
    'Lua',
    'Groovy',
    'Objective-C',
    'Perl',
    'MySQL',
    'PostgreSQL',
    'SQLite',
    'MongoDB',
    'Microsoft SQL Server',
    'Redis',
    'MariaDB',
    'Elasticsearch',
    'Oracle',
    'Firebase Realtime Database',
    'DynamoDB',
    'Cloud Firestore',
    'Cassandra',
    'Neo4j',
    'IBM DB2',
    'Couchbase',
    'CouchDB',
    'AWS',
    'Microsoft Azure',
    'Google Cloud',
    'Firebase',
    'Heroku',
    'DigitalOcean',
    'VMware',
    'Managed Hosting',
    'Linode',
    'OVH',
    'Oracle Cloud Infrastructure',
    'OpenStack',
    'IBM Cloud or Watson',
    'Colocation',
    'FastAPI',
    'Blazor',
    'Nuxt.js',
    'Symfony',
    'Gatsb',
    'Drupal',
    'Phoenix',
    'Fastify',
    'Deno',
    'Play Framework',
    '.NET',
    'NumPy',
    'Pandas',
    'Spring',
    'TensorFlow',
    'Flutter',
    'Scikit-learn',
    'React Native',
    'Apache Kafka',
    'Electron',
    'Torch/PyTorch',
    'Qt',
    'Keras',
    'Ionic',
    'Xamarin',
    'Apache Spark',
    'Cordova',
    'Hadoop',
    'GTK',
    'Capacitor',
    'Tidyverse',
    'Hugging Face Transformers',
    'Uno Platform',
    'npm',
    'Docker',
    'Yarn',
    'Homebrew',
    'Kubernetes',
    'Terraform',
    'Unity 3D',
    'Ansible',
    'Unreal Engine',
    'Puppe',
    'Chef',
    'Pulumi',
    'Flow',
    'sual Studio Code',
    'Visual Studio',
    'IntelliJ',
    'Notepad++',
    'Vim',
    'Android Studio',
    'PyCharm',
    'Sublime Text',
    'Eclipse',
    'IPython/Jupyter',
    'Xcode',
    'Atom',
    'Nano',
    'Webstorm',
    'PhpStorm',
    'Neovim',
    'NetBeans',
    'CLion',
    'Rider',
    'Emacs',
    'RStudio',
    'GoLand',
    'RAD Studio (Delphi, C++ Builder)',
    'Qt Creator',
    'Spyder',
    'RubyMine',
    'TextMate',
    'Jira Work Management',
    'Confluence',
    'Trello',
    'Notion',
    'Asana',
    'ClickUp',
    'Microsoft Planner',
    'monday.com',
    'Airtable',
    'Microsoft Lists',
    'Smartsheet',
    'Wrike',
    'Adobe Workfront',
    'DingTalk (Teambition)',
    'Swit',
    'Workzone',
    'Planview Projectplace or Clarizen',
    'Cerri',
    'Wimi',
    'Leankor',
    'Zoom',
    'Microsoft Teams',
    'Slack',
    'Google Chat',
    'Cisco Webex Teams',
    'Mattermost',
    'Rocketchat',
    'Adobe Photoshop',
    'Sketch',
    'Adobe Illustrator',
    'GIMP',
    'Lunacy',
    'Adobe InDesign',
  ]),
];
